apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.api.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.api.name }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
{{- if .Values.api.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.name }}
                port:
                  number: {{ .Values.api.port }}
{{- end }}
