apiVersion: v1
kind: Service
metadata:
  name: mpc-coordinator
  namespace: {{ .Values.namespace }}
  labels:
    app: mpc-coordinator
spec:
  type: ClusterIP
  selector:
    app: mpc-coordinator
  ports:
    - name: http
      port: {{ .Values.coordinator.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.coordinator.grpcPort }}
      targetPort: grpc
